<?xml version="1.0" standalone="yes"?>
<!DOCTYPE specialchars [
    <!ELEMENT specialchars (char)*>
    <!ELEMENT char (entity|replace|bibcode)*>
    <!ATTLIST char
        code CDATA #REQUIRED
        reviewid CDATA #IMPLIED
    >
    <!ELEMENT entity (#PCDATA)>
    <!ATTLIST entity
        allowed CDATA #IMPLIED
    >
    <!ELEMENT replace (#PCDATA)>
    <!ELEMENT bibcode (#PCDATA)>
]>

<!--

IMPORTANT NOTES for the use of this file in DagstuhlPublishing:

* for UTF8-to-Latex conversion:
    the first <bibcode>-entry will be applied!

* for Latex-to-UTF8 conversion:
    <bibcode>-entities will be ordered by length (descending)
    in the CharMap class. This is to prevent \"a to be mapped to \ä, for example.
    (Note that \"a and "a both map to ä.)

* there is no need to add the "plain versions" (e.g. "a for \"{a}) of german umlauts and similar diacritics
  they will be added automatically in StringHandler::loadMaps();

-->

<specialchars>
<char code="1">
</char>
<char code="2">
</char>
<char code="3">
</char>
<char code="4">
</char>
<char code="5">
</char>
<char code="6">
</char>
<char code="7">
</char>
<char code="8">
</char>
<char code="9">
    <replace> </replace>
</char>
<char code="10">
    <replace> </replace>
</char>
<char code="11">
</char>
<char code="12">
</char>
<char code="13">
    <replace> </replace>
</char>
<char code="14">
</char>
<char code="15">
</char>
<char code="16">
</char>
<char code="17">
</char>
<char code="18">
</char>
<char code="19">
</char>
<char code="20">
</char>
<char code="21">
</char>
<char code="22">
</char>
<char code="23">
</char>
<char code="24">
</char>
<char code="25">
</char>
<char code="26">
</char>
<char code="27">
</char>
<char code="28">
</char>
<char code="29">
</char>
<char code="30">
</char>
<char code="31">
</char>
<char code="32">
    <replace> </replace>
</char>
<char code="33">
    <replace>!</replace>
</char>
<char code="34">
    <entity>quot</entity>
    <replace>"</replace>
</char>
<char code="35">
    <bibcode>\#</bibcode>
    <replace>#</replace>
</char>
<char code="36">
    <bibcode>\$</bibcode>
    <replace>$</replace>
</char>
<char code="37">
    <bibcode>\%</bibcode>
    <replace>%</replace>
</char>
<char code="38">
    <bibcode>\&amp;</bibcode>
    <entity allowed="yes">amp</entity>
</char>
<char code="39">
    <entity>apos</entity>
</char>
<char code="40">
    <replace>(</replace>
</char>
<char code="41">
    <replace>)</replace>
</char>
<char code="42">
    <replace>*</replace>
</char>
<char code="43">
    <replace>+</replace>
</char>
<char code="44">
    <replace>,</replace>
</char>
<char code="45">
    <replace>-</replace>
</char>
<char code="46">
    <replace>.</replace>
</char>
<char code="47">
    <replace>/</replace>
</char>
<char code="48">
    <replace>0</replace>
</char>
<char code="49">
    <replace>1</replace>
</char>
<char code="50">
    <replace>2</replace>
</char>
<char code="51">
    <replace>3</replace>
</char>
<char code="52">
    <replace>4</replace>
</char>
<char code="53">
    <replace>5</replace>
</char>
<char code="54">
    <replace>6</replace>
</char>
<char code="55">
    <replace>7</replace>
</char>
<char code="56">
    <replace>8</replace>
</char>
<char code="57">
    <replace>9</replace>
</char>
<char code="58">
    <replace>:</replace>
</char>
<char code="59">
    <replace>;</replace>
</char>
<char code="60">
    <bibcode>\langle</bibcode>
    <entity allowed="yes">lt</entity>
</char>
<char code="61">
    <replace>=</replace>
</char>
<char code="62">
    <bibcode>\rangle</bibcode>
    <entity allowed="yes">gt</entity>
</char>
<char code="63">
    <replace>?</replace>
    <entity>quest</entity>
</char>
<char code="64">
    <replace>@</replace>
</char>
<char code="65">
    <replace>A</replace>
</char>
<char code="66">
    <replace>B</replace>
</char>
<char code="67">
    <replace>C</replace>
</char>
<char code="68">
    <replace>D</replace>
</char>
<char code="69">
    <replace>E</replace>
</char>
<char code="70">
    <replace>F</replace>
</char>
<char code="71">
    <replace>G</replace>
</char>
<char code="72">
    <replace>H</replace>
</char>
<char code="73">
    <replace>I</replace>
</char>
<char code="74">
    <replace>J</replace>
</char>
<char code="75">
    <replace>K</replace>
</char>
<char code="76">
    <replace>L</replace>
</char>
<char code="77">
    <replace>M</replace>
</char>
<char code="78">
    <replace>N</replace>
</char>
<char code="79">
    <replace>O</replace>
</char>
<char code="80">
    <replace>P</replace>
</char>
<char code="81">
    <replace>Q</replace>
</char>
<char code="82">
    <replace>R</replace>
</char>
<char code="83">
    <replace>S</replace>
</char>
<char code="84">
    <replace>T</replace>
</char>
<char code="85">
    <replace>U</replace>
</char>
<char code="86">
    <replace>V</replace>
</char>
<char code="87">
    <replace>W</replace>
</char>
<char code="88">
    <replace>X</replace>
</char>
<char code="89">
    <replace>Y</replace>
</char>
<char code="90">
    <replace>Z</replace>
</char>
<char code="91">
    <bibcode>\lbrack</bibcode>
    <replace>[</replace>
</char>
<char code="92">
    <bibcode>\backslash</bibcode>
    <replace>\\</replace>
</char>
<char code="93">
    <bibcode>\rbrack</bibcode>
    <replace>]</replace>
</char>
<char code="94">
    <replace>^</replace>
</char>
<char code="95">
    <bibcode>\underline</bibcode>
    <replace>_</replace>
</char>
<char code="96">
    <replace>`</replace>
</char>
<char code="97">
    <replace>a</replace>
</char>
<char code="98">
    <replace>b</replace>
</char>
<char code="99">
    <replace>c</replace>
</char>
<char code="100">
    <replace>d</replace>
</char>
<char code="101">
    <replace>e</replace>
</char>
<char code="102">
    <replace>f</replace>
</char>
<char code="103">
    <replace>g</replace>
</char>
<char code="104">
    <replace>h</replace>
</char>
<char code="105">
    <bibcode>i</bibcode>
    <bibcode>\.{i}</bibcode>
    <bibcode>\.{\i}</bibcode>
    <replace>i</replace>
</char>
<char code="106">
    <replace>j</replace>
</char>
<char code="107">
    <replace>k</replace>
</char>
<char code="108">
    <replace>l</replace>
</char>
<char code="109">
    <replace>m</replace>
</char>
<char code="110">
    <replace>n</replace>
</char>
<char code="111">
    <replace>o</replace>
</char>
<char code="112">
    <replace>p</replace>
</char>
<char code="113">
    <replace>q</replace>
</char>
<char code="114">
    <replace>r</replace>
</char>
<char code="115">
    <replace>s</replace>
</char>
<char code="116">
    <replace>t</replace>
</char>
<char code="117">
    <replace>u</replace>
</char>
<char code="118">
    <replace>v</replace>
</char>
<char code="119">
    <replace>w</replace>
</char>
<char code="120">
    <replace>x</replace>
</char>
<char code="121">
    <replace>y</replace>
</char>
<char code="122">
    <replace>z</replace>
</char>
<char code="123">
    <bibcode>\{</bibcode>
    <replace>{</replace>
</char>
<char code="124">
    <replace>|</replace>
</char>
<char code="125">
    <bibcode>\}</bibcode>
    <replace>}</replace>
</char>
<char code="126">
    <bibcode>\textasciitilde</bibcode>
    <replace>~</replace>
</char>
<char code="127">
</char>
<char code="160">
    <entity>nbsp</entity>
    <replace force="yes"> </replace>
</char>
<char code="161">
    <entity>iexcl</entity>
</char>
<char code="162">
    <num />
    <entity>cent</entity>
    <replace>cent</replace>
</char>
<char code="163">
    <num />
    <entity>pound</entity>
    <replace>GBP</replace>
</char>
<char code="164">
    <entity>curren</entity>
    <replace>currency unit</replace>
</char>
<char code="165">
    <num />
    <entity>yen</entity>
    <replace>JPY</replace>
</char>
<char code="166">
    <entity>brvbar</entity>
    <replace>|</replace>
</char>
<char code="167">
    <entity>sect</entity>
    <replace> paragraph </replace>
</char>
<char code="168">
    <entity>uml</entity>
    <replace> (uml) </replace>
</char>
<char code="169">
    <entity>copy</entity>
    <replace>(c)</replace>
</char>
<char code="170">
    <entity>ordf</entity>
    <replace>.</replace>
</char>
<char code="171">
    <entity>laquo</entity>
    <replace>"</replace>
</char>
<char code="172">
    <entity>not</entity>
    <replace>not</replace>
</char>
<char code="173">
    <entity>shy</entity>
    <replace>-</replace>
</char>
<char code="174">
    <entity allowed="yes">reg</entity>
</char>
<char code="175">
    <entity>macr</entity>
    <replace>-</replace>
</char>
<char code="176">
    <num />
    <entity>deg</entity>
    <replace>degree</replace>
</char>
<char code="177">
    <num />
    <entity>plusmn</entity>
    <bibcode>\pm</bibcode>
    <replace>+/-</replace>
</char>
<char code="178">
    <entity>sup2</entity>
    <replace>&lt;sup&gt;2&lt;/sup&gt;</replace>
</char>
<char code="179">
    <entity>sup3</entity>
    <replace>&lt;sup&gt;3&lt;/sup&gt;</replace>
</char>
<char code="180">
    <entity>acute</entity>
    <replace force="yes">'</replace>
</char>
<char code="181">
    <entity allowed="yes">micro</entity>
</char>
<char code="182">
    <entity>para</entity>
</char>
<char code="183">
    <num />
    <entity>middot</entity>
    <replace>*</replace>
</char>
<char code="184">
    <entity>cedil</entity>
</char>
<char code="185">
    <entity>1</entity>
    <replace>&lt;sup&gt;1&lt;/sup&gt;</replace>
</char>
<char code="186">
    <entity>ordm</entity>
    <replace>.</replace>
</char>
<char code="187">
    <entity>raquo</entity>
    <replace>"</replace>
</char>
<char code="188">
    <num />
    <entity>frac14</entity>
    <replace>1/4</replace>
</char>
<char code="189">
    <num />
    <entity>frac12</entity>
    <replace>1/2</replace>
</char>
<char code="190">
    <num />
    <entity>frac34</entity>
    <replace>3/4</replace>
</char>
<char code="191">
    <entity>iquest</entity>
</char>
<char code="192">
    <bibcode>\`{A}</bibcode>
    <entity allowed="yes">Agrave</entity>
</char>
<char code="193">
    <bibcode>\'{A}</bibcode>
    <entity allowed="yes">Aacute</entity>
</char>
<char code="194">
    <bibcode>\^{A}</bibcode>
    <entity allowed="yes">Acirc</entity>
</char>
<char code="195">
    <bibcode>\~{A}</bibcode>
    <entity allowed="yes">Atilde</entity>
</char>
<char code="196">
    <bibcode>\"{A}</bibcode>
    <entity allowed="yes">Auml</entity>
</char>
<char code="197">
    <bibcode>\r{A}</bibcode>
    <bibcode>{\AA}</bibcode>
    <entity allowed="yes">Aring</entity>
</char>
<char code="198">
    <bibcode>\AE</bibcode>
    <entity allowed="yes">AElig</entity>
</char>
<char code="199">
    <bibcode>\c{C}</bibcode>
    <entity allowed="yes">Ccedil</entity>
</char>
<char code="200">
    <bibcode>\`{E}</bibcode>
    <entity allowed="yes">Egrave</entity>
</char>
<char code="201">
    <bibcode>\'{E}</bibcode>
    <entity allowed="yes">Eacute</entity>
</char>
<char code="202">
    <bibcode>\^{E}</bibcode>
    <entity allowed="yes">Ecirc</entity>
</char>
<char code="203">
    <bibcode>\"{E}</bibcode>
    <entity allowed="yes">Euml</entity>
</char>
<char code="204">
    <bibcode>\`{I}</bibcode>
    <entity allowed="yes">Igrave</entity>
</char>
<char code="205">
    <bibcode>\'{I}</bibcode>
    <bibcode>\'{\I}</bibcode>
    <entity allowed="yes">Iacute</entity>
</char>
<char code="206">
    <bibcode>\^{I}</bibcode>
    <entity allowed="yes">Icirc</entity>
</char>
<char code="207">
    <bibcode>\"{I}</bibcode>
    <entity allowed="yes">Iuml</entity>
</char>
<char code="208">
    <entity allowed="yes">ETH</entity>
</char>
<char code="209">
    <bibcode>\~{N}</bibcode>
    <entity allowed="yes">Ntilde</entity>
</char>
<char code="210">
    <bibcode>\`{O}</bibcode>
    <entity allowed="yes">Ograve</entity>
</char>
<char code="211">
    <bibcode>\'{O}</bibcode>
    <entity allowed="yes">Oacute</entity>
</char>
<char code="212">
    <bibcode>\^{O}</bibcode>
    <entity allowed="yes">Ocirc</entity>
</char>
<char code="213">
    <bibcode>\~{O}</bibcode>
    <bibcode>\tilde{O}</bibcode>
    <entity allowed="yes">Otilde</entity>
</char>
<char code="214">
    <bibcode>\"{O}</bibcode>
    <entity allowed="yes">Ouml</entity>
</char>
<char code="215">
    <entity allowed="yes">times</entity>
</char>
<char code="216">
    <bibcode>{\O}</bibcode>
    <bibcode>\O</bibcode>
    <entity allowed="yes">Oslash</entity>
</char>
<char code="217">
    <bibcode>\`{U}</bibcode>
    <entity allowed="yes">Ugrave</entity>
</char>
<char code="218">
    <bibcode>\'{U}</bibcode>
    <entity allowed="yes">Uacute</entity>
</char>
<char code="219">
    <bibcode>\^{U}</bibcode>
    <entity allowed="yes">Ucirc</entity>
</char>
<char code="220">
    <bibcode>\"{U}</bibcode>
    <entity allowed="yes">Uuml</entity>
</char>
<char code="221">
    <bibcode>\'{Y}</bibcode>
    <entity allowed="yes">Yacute</entity>
</char>
<char code="222">
    <entity allowed="yes">THORN</entity>
</char>
<char code="223">
    <bibcode>{\ss}</bibcode>
    <bibcode>\ss </bibcode>
    <entity allowed="yes">szlig</entity>
</char>
<char code="224">
    <bibcode>\`{a}</bibcode>
    <entity allowed="yes">agrave</entity>
</char>
<char code="225">
    <bibcode>\'{a}</bibcode>
    <entity allowed="yes">aacute</entity>
</char>
<char code="226">
    <bibcode>\^{a}</bibcode>
    <entity allowed="yes">acirc</entity>
</char>
<char code="227">
    <bibcode>\~{a}</bibcode>
    <bibcode>\~a</bibcode>
    <entity allowed="yes">atilde</entity>
</char>
<char code="228">
    <bibcode>\"{a}</bibcode>
    <entity allowed="yes">auml</entity>
</char>
<char code="229">
    <bibcode>\r{a}</bibcode>
    <bibcode>\aa </bibcode>
    <entity allowed="yes">aring</entity>
</char>
<char code="230">
    <bibcode>{\ae}</bibcode>
    <bibcode>\ae </bibcode>
    <entity allowed="yes">aelig</entity>
</char>
<char code="231">
    <bibcode>\c{c}</bibcode>
    <bibcode>\c c</bibcode>
    <entity allowed="yes">ccedil</entity>
</char>
<char code="232">
    <bibcode>\`{e}</bibcode>
    <entity allowed="yes">egrave</entity>
</char>
<char code="233">
    <bibcode>\'{e}</bibcode>
    <bibcode>\'e</bibcode>
    <entity allowed="yes">eacute</entity>
</char>
<char code="234">
    <bibcode>\^{e}</bibcode>
    <entity allowed="yes">ecirc</entity>
</char>
<char code="235">
    <bibcode>\"{e}</bibcode>
    <entity allowed="yes">euml</entity>
</char>
<char code="236">
    <bibcode>\`{\i}</bibcode>
    <bibcode>\`{i}</bibcode>
    <bibcode>{\`\i}</bibcode>
    <entity allowed="yes">igrave</entity>
</char>
<char code="237">
    <bibcode>{\'\i}</bibcode>
    <bibcode>\'{i}</bibcode>
    <bibcode>\'{\i}</bibcode>
    <bibcode>\'i</bibcode>
    <entity allowed="yes">iacute</entity>
</char>
<char code="238">
    <bibcode>\^{i}</bibcode>
    <bibcode>\^{\i}</bibcode>
    <bibcode>{\^\i}</bibcode>
    <entity allowed="yes">icirc</entity>
</char>
<char code="239">
    <bibcode>\"{i}</bibcode>
    <bibcode>\"{\i}</bibcode>
    <bibcode>{\"\i}</bibcode>
    <entity allowed="yes">iuml</entity>
</char>
<char code="240">
    <entity allowed="yes">eth</entity>
</char>
<char code="241">
    <bibcode>\~{n}</bibcode>
    <entity allowed="yes">ntilde</entity>
</char>
<char code="242">
    <bibcode>\`{o}</bibcode>
    <entity allowed="yes">ograve</entity>
</char>
<char code="243">
    <bibcode>\'{o}</bibcode>
    <bibcode>\'o</bibcode>
    <bibcode>{\'o}</bibcode>
    <entity allowed="yes">oacute</entity>
</char>
<char code="244">
    <bibcode>\^{o}</bibcode>
    <bibcode>{\^o}</bibcode>
    <entity allowed="yes">ocirc</entity>
</char>
<char code="245">
    <bibcode>\~{o}</bibcode>
    <bibcode>\tilde{o}</bibcode>
    <entity allowed="yes">otilde</entity>
</char>
<char code="246">
    <bibcode>\"{o}</bibcode>
    <bibcode>{\"o}</bibcode>
    <entity allowed="yes">ouml</entity>
</char>
<char code="247">
    <entity>divide</entity>
    <replace>/</replace>
</char>
<char code="248">
    <bibcode>{\o}</bibcode>
    <bibcode>\o </bibcode>
    <bibcode>\o{}</bibcode><!-- dblp: "\o" -->
    <entity allowed="yes">oslash</entity>
</char>
<char code="249">
    <bibcode>\`{u}</bibcode>
    <entity allowed="yes">ugrave</entity>
</char>
<char code="250">
    <bibcode>\'{u}</bibcode>
    <bibcode>\'u</bibcode>
    <bibcode>{\'u}</bibcode>
    <entity allowed="yes">uacute</entity>
</char>
<char code="251">
    <bibcode>\^{u}</bibcode>
    <entity allowed="yes">ucirc</entity>
</char>
<char code="252">
    <bibcode>\"{u}</bibcode>
    <entity allowed="yes">uuml</entity>
</char>
<char code="253">
    <bibcode>\'{y}</bibcode>
    <entity allowed="yes">yacute</entity>
</char>
<char code="254">
    <entity allowed="yes">thorn</entity>
</char>
<char code="255">
    <bibcode>\"{y}</bibcode>
    <entity allowed="yes">yuml</entity>
</char>
<char code="256">
    <bibcode>\={A}</bibcode>
    <entity>Amacr</entity>
    <replace>A</replace>
</char>
<char code="257">
    <bibcode>\={a}</bibcode>
    <entity>amacr</entity>
    <replace>a</replace>
</char>
<char code="258">
    <bibcode>\u{A}</bibcode>
    <entity>Abreve</entity>
    <replace>A</replace>
</char>
<char code="259">
    <bibcode>\u{a}</bibcode>
    <bibcode>\u a</bibcode>
    <entity>abreve</entity>
    <replace>a</replace>
</char>
<char code="260">
    <bibcode>\k{A}</bibcode>
    <entity>Aogon</entity>
    <replace>A</replace>
</char>
<char code="261">
    <bibcode>\k{a}</bibcode>
    <bibcode>{\k a}</bibcode>
    <entity>aogon</entity>
    <replace>a</replace>
</char>
<char code="262">
    <bibcode>\'{C}</bibcode>
    <entity>Cacute</entity>
    <replace>C</replace>
</char>
<char code="263">
    <bibcode>\'{c}</bibcode>
    <bibcode>\' c</bibcode>
    <entity>cacute</entity>
    <replace>c</replace>
</char>
<char code="264">
    <bibcode>\^{C}</bibcode>
    <entity>Ccirc</entity>
    <replace>C</replace>
</char>
<char code="265">
    <bibcode>\^{c}</bibcode>
    <entity>ccirc</entity>
    <replace>c</replace>
</char>
<char code="266">
    <bibcode>\.{C}</bibcode>
    <entity>Cdot</entity>
    <replace>C</replace>
</char>
<char code="267">
    <bibcode>\.{c}</bibcode>
    <entity>cdot</entity>
    <replace>c</replace>
</char>
<char code="268">
    <bibcode>\v{C}</bibcode>
    <bibcode>{\v C}</bibcode>
    <entity>Ccaron</entity>
    <replace>C</replace>
</char>
<char code="269">
    <bibcode>\v{c}</bibcode>
    <bibcode>\v c</bibcode>
    <entity>ccaron</entity>
    <replace>c</replace>
</char>
<char code="270">
    <bibcode>\v{D}</bibcode>
    <entity>Dcaron</entity>
    <replace>D</replace>
</char>
<char code="271">
    <bibcode>\v{d}</bibcode>
    <entity>dcaron</entity>
    <replace>d</replace>
</char>
<char code="272">
    <bibcode>{\D}</bibcode><!-- dblp: "\D" -->
    <bibcode>{\DJ}</bibcode>
    <bibcode>\D </bibcode><!-- dblp: not contained -->
    <entity>Dstrok</entity>
    <replace>D</replace>
</char>
<char code="273">
    <bibcode>{\d}</bibcode><!-- dblp: "\d" -->
    <bibcode>{\dj}</bibcode>
    <bibcode>\d </bibcode><!-- dblp: not contained -->
    <entity>dstrok</entity>
    <replace>d</replace>
</char>
<char code="274">
    <bibcode>\={E}</bibcode>
    <entity>Emacr</entity>
    <replace>E</replace>
</char>
<char code="275">
    <bibcode>\={e}</bibcode>
    <entity>emacr</entity>
    <replace>e</replace>
</char>
<char code="276">
    <bibcode>\u{E}</bibcode>
    <entity>Ebreve</entity>
    <replace>E</replace>
</char>
<char code="277">
    <bibcode>\u{e}</bibcode>
    <entity>ebreve</entity>
    <replace>e</replace>
</char>
<char code="278">
    <bibcode>\.{E}</bibcode>
    <entity>Edot</entity>
    <replace>E</replace>
</char>
<char code="279">
    <bibcode>\.{e}</bibcode>
    <entity>edot</entity>
    <replace>e</replace>
</char>
<char code="280">
    <bibcode>\k{E}</bibcode>
    <entity>Eogon</entity>
    <replace>E</replace>
</char>
<char code="281">
    <bibcode>\k{e}</bibcode>
    <entity>eogon</entity>
    <replace>e</replace>
</char>
<char code="282">
    <bibcode>\v{E}</bibcode>
    <entity>Ecaron</entity>
    <replace>E</replace>
</char>
<char code="283">
    <bibcode>\v{e}</bibcode>
    <bibcode>\v e</bibcode>
    <entity>ecaron</entity>
    <replace>e</replace>
</char>
<char code="284">
    <bibcode>\^{G}</bibcode>
    <entity>Gcirc</entity>
    <replace>G</replace>
</char>
<char code="285">
    <bibcode>\^{g}</bibcode>
    <entity>gcirc</entity>
    <replace>g</replace>
</char>
<char code="286">
    <bibcode>\u{G}</bibcode>
    <entity>Gbreve</entity>
    <replace>G</replace>
</char>
<char code="287">
    <bibcode>\u{g}</bibcode>
    <bibcode>\u g</bibcode>
    <entity>gbreve</entity>
    <replace>g</replace>
</char>
<char code="288">
    <bibcode>\.{G}</bibcode>
    <entity>Gdot</entity>
    <replace>G</replace>
</char>
<char code="289">
    <bibcode>\.{g}</bibcode>
    <entity>gdot</entity>
    <replace>g</replace>
</char>
<char code="290">
    <bibcode>\c{G}</bibcode>
    <entity>Gcedil</entity>
    <replace>G</replace>
</char>
<char code="291">
    <bibcode>\c{g}</bibcode>
    <entity>gcedil</entity>
    <replace>g</replace>
</char>
<char code="292">
    <bibcode>\^{H}</bibcode>
    <entity>Hcirc</entity>
    <replace>H</replace>
</char>
<char code="293">
    <bibcode>\^{h}</bibcode>
    <entity>hcirc</entity>
    <replace>h</replace>
</char>
<char code="294">
    <bibcode>\Hstrok</bibcode>
    <entity>Hstrok</entity>
    <replace>H</replace>
</char>
<char code="295">
    <bibcode>\hstrok</bibcode>
    <entity>hstrok</entity>
    <replace>h</replace>
</char>
<char code="296">
    <bibcode>\~{I}</bibcode>
    <entity>Itilde</entity>
    <replace>I</replace>
</char>
<char code="297">
    <bibcode>\~{i}</bibcode>
    <bibcode>\~{\i}</bibcode>
    <entity>itilde</entity>
    <replace>i</replace>
</char>
<char code="298">
    <bibcode>\={I}</bibcode>
    <entity>Imacr</entity>
    <replace>I</replace>
</char>
<char code="299">
    <bibcode>\={i}</bibcode>
    <bibcode>\={\i}</bibcode>
    <entity>imacr</entity>
    <replace>i</replace>
</char>
<char code="300">
    <bibcode>\u{I}</bibcode>
    <entity>Ibreve</entity>
    <replace>I</replace>
</char>
<char code="301">
    <bibcode>\u{i}</bibcode>
    <entity>ibreve</entity>
    <replace>i</replace>
</char>
<char code="302">
    <bibcode>\k{I}</bibcode>
    <entity>Iogon</entity>
    <replace>I</replace>
</char>
<char code="303">
    <bibcode>\k{i}</bibcode>
    <entity>iogon</entity>
    <replace>i</replace>
</char>
<char code="304">
    <bibcode>\.{I}</bibcode>
    <entity>Idot</entity>
    <replace>I</replace>
</char>
<char code="305">
    <bibcode>{\i}</bibcode><!-- dblp: "\{\i}" -->
    <bibcode>\i </bibcode><!-- dblp: not present -->
    <entity>inodot</entity>
    <entity>imath</entity>
    <replace>i</replace>
</char>
<char code="306">
    <bibcode>{\IJ}</bibcode><!-- dblp: not present -->
    <bibcode>\IJ </bibcode><!-- dblp: "\IJ" -->
    <entity>IJlig</entity>
    <replace>IJ</replace>
</char>
<char code="307">
    <bibcode>{\ij}</bibcode><!-- dblp: not present -->
    <bibcode>\ij </bibcode><!-- dblp: "\ij" -->
    <entity>ijlig</entity>
    <replace>ij</replace>
</char>
<char code="308">
    <bibcode>\^{J}</bibcode>
    <entity>Jcirc</entity>
    <replace>J</replace>
</char>
<char code="309">
    <bibcode>\^{j}</bibcode>
    <entity>jcirc</entity>
    <replace>j</replace>
</char>
<char code="310">
    <bibcode>\c{K}</bibcode>
    <entity>Kcedil</entity>
    <replace>K</replace>
</char>
<char code="311">
    <bibcode>\c{k}</bibcode>
    <entity>kcedil</entity>
    <replace>k</replace>
</char>
<char code="312">
    <entity>kgreen</entity>
    <replace>k</replace>
</char>
<char code="313">
    <bibcode>\'{L}</bibcode>
    <entity>Lacute</entity>
    <replace>\'{L}</replace>
</char>
<char code="314">
    <bibcode>\'{l}</bibcode>
    <entity>lacute</entity>
    <replace>l</replace>
</char>
<char code="315">
    <bibcode>\c{L}</bibcode>
    <entity>Lcedil</entity>
    <replace>L</replace>
</char>
<char code="316">
    <bibcode>\c{l}</bibcode>
    <entity>lcedil</entity>
    <replace>l</replace>
</char>
<char code="317">
    <bibcode>\v{L}</bibcode>
    <entity>Lcaron</entity>
    <replace>L</replace>
</char>
<char code="318">
    <bibcode>\v{l}</bibcode>
    <entity>lcaron</entity>
    <replace>l</replace>
</char>
<char code="319">
    <bibcode>\.{L}</bibcode>
    <entity>Lmidot</entity>
    <replace>L</replace>
</char>
<char code="320">
    <bibcode>\.{l}</bibcode>
    <entity>lmidot</entity>
    <replace>l</replace>
</char>
<char code="321">
    <bibcode>{\L}</bibcode>
    <bibcode>\L{}</bibcode>
    <bibcode>\L </bibcode><!-- dblp: not contained -->
    <entity>Lstrok</entity>
    <replace>L</replace>
</char>
<char code="322">
    <bibcode>{\l}</bibcode>
    <bibcode>\l{}</bibcode>
    <bibcode>\l </bibcode><!-- dblp: not contained -->
    <entity>lstrok</entity>
    <replace>l</replace>
</char>
<char code="323">
    <bibcode>\'{N}</bibcode>
    <bibcode>\' N</bibcode>
    <entity>Nacute</entity>
    <replace>N</replace>
</char>
<char code="324">
    <bibcode>\'{n}</bibcode>
    <bibcode>\' n</bibcode>
    <entity>nacute</entity>
    <replace>n</replace>
</char>
<char code="325">
    <bibcode>\c{N}</bibcode>
    <entity>Ncedil</entity>
    <replace>N</replace>
</char>
<char code="326">
    <bibcode>\c{n}</bibcode>
    <entity>ncedil</entity>
    <replace>n</replace>
</char>
<char code="327">
    <bibcode>\v{N}</bibcode>
    <entity>Ncaron</entity>
    <replace>N</replace>
</char>
<char code="328">
    <bibcode>\v{n}</bibcode>
    <entity>ncaron</entity>
    <replace>n</replace>
</char>
<char code="329">
    <entity>napos</entity>
    <replace>n</replace>
</char>
<char code="330">
    <entity>ENG</entity>
    <replace>N</replace>
</char>
<char code="331">
    <entity>eng</entity>
    <replace>n</replace>
</char>
<char code="332">
    <bibcode>\={O}</bibcode>
    <entity>Omacr</entity>
    <replace>O</replace>
</char>
<char code="333">
    <bibcode>\={o}</bibcode>
    <entity>omacr</entity>
    <replace>o</replace>
</char>
<char code="334">
    <bibcode>\u{O}</bibcode>
    <entity>Obreve</entity>
    <replace>O</replace>
</char>
<char code="335">
    <bibcode>\u{o}</bibcode>
    <entity>obreve</entity>
    <replace>o</replace>
</char>
<char code="336">
    <bibcode>\H{O}</bibcode>
    <entity>Odblac</entity>
    <replace>O</replace>
</char>
<char code="337">
    <bibcode>\H{o}</bibcode>
    <entity>odblac</entity>
    <replace>o</replace>
</char>
<char code="338">
    <bibcode>\OE</bibcode>
    <entity>OElig</entity>
    <replace>OE</replace>
</char>
<char code="339">
    <bibcode>{\oe}</bibcode>
    <bibcode>\oe</bibcode>
    <entity>oelig</entity>
    <replace>oe</replace>
</char>
<char code="340">
    <bibcode>\'{R}</bibcode>
    <entity>Racute</entity>
    <replace>R</replace>
</char>
<char code="341">
    <bibcode>\'{r}</bibcode>
    <entity>racute</entity>
    <replace>r</replace>
</char>
<char code="342">
    <bibcode>\c{R}</bibcode>
    <entity>Rcedil</entity>
    <replace>R</replace>
</char>
<char code="343">
    <bibcode>\c{r}</bibcode>
    <entity>rcedil</entity>
    <replace>r</replace>
</char>
<char code="344">
    <bibcode>\v{R}</bibcode>
    <entity>Rcaron</entity>
    <replace>R</replace>
</char>
<char code="345">
    <bibcode>\v{r}</bibcode>
    <bibcode>{\v r}</bibcode>
    <bibcode>\v r</bibcode>
    <entity>rcaron</entity>
    <replace>r</replace>
</char>
<char code="346">
    <bibcode>\'{S}</bibcode>
    <entity>Sacute</entity>
    <replace>S</replace>
</char>
<char code="347">
    <bibcode>\'{s}</bibcode>
    <bibcode>\’s</bibcode>
    <entity>sacute</entity>
    <replace>s</replace>
</char>
<char code="348">
    <bibcode>\^{S}</bibcode>
    <entity>Scirc</entity>
    <replace>S</replace>
</char>
<char code="349">
    <bibcode>\^{s}</bibcode>
    <entity>scirc</entity>
    <replace>s</replace>
</char>
<char code="350">
    <bibcode>\c{S}</bibcode>
    <bibcode>\c S</bibcode>
    <entity>Scedil</entity>
    <replace>S</replace>
</char>
<char code="351">
    <bibcode>\c{s}</bibcode>
    <bibcode>\c s</bibcode>
    <bibcode>{\c s}</bibcode>
    <entity>scedil</entity>
    <replace>s</replace>
</char>
<char code="352">
    <bibcode>\v{S}</bibcode>
    <entity>Scaron</entity>
    <replace>S</replace>
</char>
<char code="353">
    <bibcode>\v{s}</bibcode>
    <bibcode>\v s</bibcode>
    <bibcode>{\v s}</bibcode>
    <entity>scaron</entity>
    <replace>s</replace>
</char>
<char code="354">
    <bibcode>\c{T}</bibcode>
    <entity>Tcedil</entity>
    <replace>T</replace>
</char>
<char code="355">
    <bibcode>\c{t}</bibcode>
    <bibcode>\c t</bibcode>
    <entity>tcedil</entity>
    <replace>t</replace>
</char>
<char code="356">
    <bibcode>\v{T}</bibcode>
    <entity>Tcaron</entity>
    <replace>T</replace>
</char>
<char code="357">
    <bibcode>\v{t}</bibcode>
    <entity>tcaron</entity>
    <replace>t</replace>
</char>
<char code="358">
    <entity>Tstrok</entity>
    <replace>T</replace>
</char>
<char code="359">
    <entity>tstrok</entity>
    <replace>t</replace>
</char>
<char code="360">
    <bibcode>\~{U}</bibcode>
    <entity>Utilde</entity>
    <replace>U</replace>
</char>
<char code="361">
    <bibcode>\~{u}</bibcode>
    <entity>utilde</entity>
    <replace>u</replace>
</char>
<char code="362">
    <bibcode>\={U}</bibcode>
    <entity>Umacr</entity>
    <replace>U</replace>
</char>
<char code="363">
    <bibcode>\={u}</bibcode>
    <entity>umacr</entity>
    <replace>u</replace>
</char>
<char code="364">
    <bibcode>\u{U}</bibcode>
    <entity>Ubreve</entity>
    <replace>U</replace>
</char>
<char code="365">
    <bibcode>\u{u}</bibcode>
    <entity>ubreve</entity>
    <replace>u</replace>
</char>
<char code="366">
    <bibcode>\r{U}</bibcode>
    <entity>Uring</entity>
    <replace>U</replace>
</char>
<char code="367">
    <bibcode>\r{u}</bibcode>
    <entity>uring</entity>
    <replace>u</replace>
</char>
<char code="368">
    <bibcode>\H{U}</bibcode>
    <entity>Udblac</entity>
    <replace>&amp;Uuml;</replace>
</char>
<char code="369">
    <bibcode>\H{u}</bibcode>
    <entity>udblac</entity>
    <replace>&amp;uuml;</replace>
</char>
<char code="370">